### ISSUE TITLE
Cascade governor's reset is documented from the wrong side — a capped seat self-releases every window, measured at 18 turns/hour

### ISSUE THREAD

**Issue by lilyshen0722** [Team-Commonly/commonly#989]
## Summary

`createCascadeGovernor`'s `resetMs` docstring and the refusal log line, both introduced by #973 (`63c94ded`), describe a release condition the code does not implement. The **behaviour is fine** — arguably better than documented — but the description says a capped seat stays down until a human speaks, and measurement says it self-releases every reset window regardless of how busy the pod is.

## What the code says

`cli/src/lib/enforcement.js` (origin/main):

> NOTE on `resetMs`: it is a SILENCE window, not a decay. It requires `resetMs` with ZERO agent-triggered turns in the pod. Three chatty seats never leave a ten-minute hole, so in a busy room the only live release is a human turn. Say so plainly rather than letting "or the streak decays" imply a timer that will save you.

and `cli/src/commands/agent.js:812`:

> `— standing down until a human speaks or the pod goes quiet for the reset window`

## Why it isn't so

The reset predicate reads `lastAgentTurnAt`, which is written **only** by `record()`:

```js
if (s.streak > 0 && now() - s.lastAgentTurnAt > resetMs) return { streak: 0, lastAgentTurnAt: 0 };
```

`record()` runs at `agent.js:1041`, after the turn completes. A capped turn returns at `agent.js:814` (`reason: 'cascade-cap'`) and never reaches it. Two consequences the note misses:

1. **The clock is per-seat and in-process.** Other seats' turns are invisible to it, so "zero agent-triggered turns in the pod" is not the condition — "zero *admitted, completed* agent turns by *this seat*" is. Three chatty peers leave the capped seat's ten-minute hole completely undisturbed.
2. **A capped seat satisfies that condition by construction.** While it is refusing it is recording nothing, so its clock is frozen and the window always elapses.

## Measured

Driving the real `origin/main` governor through the run loop's exact call pattern (`admit` → return on refusal without `record`; `record` only after an admitted turn), with an injected clock, sustained agent-authored traffic, and **no human turn ever**:

| arrival | admits/hour |
|---|---|
| 1 per 600s | 6 |
| 1 per 300s | 9 |
| 1 per 120s | 12 |
| 1 per 60s | 15 |
| 1 per 30s | 18 |
| 1 per 10s | 18 |
| 1 per 5s | 18 |
| 1 per 1s | 18 |

Admit times at 1/min (seconds): `0, 60, 120, 780, 840, 900, 1560, 1620, 1680, 2340, 2400, 2460, 3120, 3180, 3240` — three admits, then a 660s hole, repeating.

**Counterfactual control**, same harness with the one line changed so a refusal also records — i.e. the implementation the docstring describes: **3 admits total, last at t=120s, silent for the remaining 58 minutes.** So the harness does discriminate the two models sharply (15 vs 3, 18 vs 3); this is not a modelling artifact.

Same numbers against `c175a266`, the governor the running seats actually hold, called the way that copy's call site calls it (`admit(pod, trigger)`, two args): **15/hour**. So the behaviour is not new — #973 left broadcast damping untouched and only raised mentions (15 → 21/hour at 1/min). What #973 changed is the description, and it replaced `c175a266`'s vaguer *"or the streak decays"* — which was directionally right — with a precise claim that is wrong.

## What this actually means

The `(cap, resetMs)` pair is a **token bucket**, not a ceiling: burst of `cap`, then `cap` more after `resetMs` of the seat's own silence. Its useful property is the flat tail — the admit rate pins at `cap` per `resetMs` (18/hour at the defaults) no matter how hard the burst gets, while staying inert in a quiet pod. That is a genuinely load-adaptive shape and worth stating as the design, because it answers the standing objection that a static constant must be wrong in one phase of a bimodal load.

The cost of the current wording is a real operational belief: an operator reading either the docstring or the refusal log concludes an agent↔agent echo loop **terminates** and waits for a human. It does not — it throttles to 18 turns/hour and runs indefinitely. That is the right call in my view (the alternative strands a live a2a handoff behind a human who may never arrive), but it should be the documented call rather than a surprise.

## Suggested fix

Docs/log only, no behaviour change:

- Replace the `resetMs` NOTE with what the predicate does: the window is `resetMs` with no **admitted** agent turn **by this seat**; a capped seat therefore always self-releases, and peers' traffic is irrelevant. Name the resulting steady state (`cap` admits per `resetMs`).
- `agent.js:812`: `— standing down until a human speaks or this seat's reset window elapses` (drop "the pod goes quiet").
- Worth a unit test pinning the steady-state rate, since this is the second time the release condition has been described from the wrong side and nothing currently fails when it is.

## Not verified

I exercised the governor module directly with an injected clock, not a live seat end-to-end, so this pins the governor's decisions and not the run loop's surrounding behaviour (redelivery, ack, claim interaction). #981 is OPEN and carries the same log line unchanged, so the wording ships with it either way.

Related: #973 (introduced the wording), #980 (the refusal-rate analysis, whose denominators this rate structure bears on), #981 (makes the pair tunable).

**Comment by lilyshen0722** [comment]
Confirmed from source, and there is a **second** wrong axis in the same sentence that the fix should cover.

**The axis this issue names — which turns count.** Verified: the refusal returns at `cli/src/commands/agent.js:859` and `cascadeGovernor.record` is `:1087`, so a refused event never reaches `record` and never updates `lastAgentTurnAt`. `stateFor` applies the reset read-only, and `record` re-reads *through* `stateFor` before incrementing, so the streak genuinely zeroes. Token-bucket shape confirmed: `cap` admits per `resetMs`.

**The axis it does not name — whose turns count.** The doc comment (`cli/src/lib/enforcement.js:171-175`) says the window requires zero agent-triggered turns *"in the pod"*, and concludes *"three chatty seats never leave a ten-minute hole."* But `pods` is a `Map` in the closure of `createCascadeGovernor`, inside a single wrapper process. It only ever observes turns **this seat** processed. Peer seats' turns — admitted ones included — were never counted in the first place.

So the sentence fails twice over, and the two failures are independent:

| claim | why it's wrong |
|---|---|
| "zero agent-triggered turns **in the pod**" | scope: the governor is per-seat and in-process; it cannot see peer seats at all |
| "three chatty seats never leave a ten-minute hole" | *both*: peer turns were never counted, and this seat's own refused turns aren't either |
| "in a busy room the only live release is a human turn" | inverted: in a busy room a capped seat self-releases every `resetMs` |

Worth fixing together, because correcting only the refusal axis leaves "in the pod" reading as though a quiet *room* is what releases the streak — the same wrong mental model one layer down.

**Merge-order note:** the log string at `agent.js:812` on `main` is one line below a line #981 rewrites (`6fb83c50`, `admission.addressed` → `admission.graceApplied`). I simulated this fix on `main` and merged #981 into it: real content conflict in `agent.js`, not a shared-path false alarm. Either land #981 first and stack, or let #981 carry the string.
